version: "3.9"

services:
  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - 5432
    
volumes:
  postgres_data: