# Generated by Django 4.2.6 on 2023-10-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Premium", "Premium"),
                            ("Enterprise", "Enterprise"),
                            ("Custom", "Custom"),
                        ],
                        default="Basic",
                        max_length=15,
                    ),
                ),
                ("height_1", models.PositiveIntegerField(default=200)),
                ("height_2", models.PositiveIntegerField(default=400)),
                ("original_link", models.BooleanField(default=False)),
                ("generate_link", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
