# Generated by Django 4.2.6 on 2023-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="generate_link",
            field=models.BooleanField(default=False, verbose_name="Can generate links"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height_2",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
