# Generated by Django 4.2.6 on 2023-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_generate_link_alter_profile_height_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="height_1",
            field=models.PositiveIntegerField(
                default=200, verbose_name="Thumbnail #1 height"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height_2",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Thumbnail #2 height"
            ),
        ),
    ]
