# Generated by Django 4.2.6 on 2023-10-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid", models.PositiveIntegerField(help_text="Valid for (seconds)")),
                ("valid_till", models.DateTimeField(blank=True, editable=False)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="images.image"
                    ),
                ),
            ],
        ),
    ]
