# Generated by Django 4.2.6 on 2023-10-10 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="valid",
            field=models.PositiveIntegerField(
                help_text="Valid for (seconds)",
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(30000),
                ],
            ),
        ),
    ]
