# Generated by Django 4.2.6 on 2023-10-11 11:43

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_link_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/adrian/upload/protected"
                ),
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"],
                        message="File extension not allowed.",
                    )
                ],
            ),
        ),
    ]
