# Generated by Django 4.2.6 on 2023-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
